### ISSUE TITLE
Not working with 13.12.1

### ISSUE THREAD

**Issue by verticelo** [traud/asterisk-silk#2]
Hi!

Just wanted to report that we tried this patch with Asterisk 13.12.1 and it doesn't work for two reasons:
1) Patch won't apply
2) When changing the patch to only modify the parts that are not already in 13.12.1 it applies cleanly however the sound quality using SiLK is now unfortunately very poor compared to using it on 13.7.

One might ask, why not use the binaries that Digium now provides for SiLK? Reason is that they enforce VBR in those binaries and there is no setting to turn it off. During our testing we see SiLK (with the binaries) dropping in bitrate to an extremely low level where the sound is barely audible. Hence the Digium SiLK implementation is not usable..

We tested the sound quality by just having an extension where it plays MOH continously using this patch. Sounds great on 13.7, sounds extremely poor on 13.12.1.

**Comment by traud** [comment]
I am glad this module is used by others. Thanks for the issue report. I added the steps required for Asterisk 13.12 (and newer) in the [README](//github.com/traud/asterisk-silk). Please, close this report when this works for you as well.

> Digium enforces VBR … no setting to turn it off.

Please, report that separately in the [Asterisk Issue Tracker…](https://issues.asterisk.org/)
Normally, the file [codecs.conf](//github.com/asterisk/asterisk/blob/master/configs/samples/codecs.conf.sample) should be able to adjust something like that. The sample file in the directory `configs/sample` might not be updated, yet. However, I haven’t double-checked.

> dropping in bitrate to an extremely low level where the sound is barely audible

Mhm. While in a call? I am not sure why that binary module reduces the bit-rate. Sounds like another bug. Did you create a separate issue report for that?

**Comment by verticelo** [comment]
Thank you for the update. Just tested the patch and it doesn't work unfortunately.

I did apply the reversals and then the original patch, everything applied cleanly.

core show codecs: shows the codecs including SiLK
core show translation paths silk16: "No translation path"

Any idea if why Asterisk doesn't find any translation paths with SiLK any longer using your updated instructions?

> Mhm. While in a call? I am not sure why that binary module reduces the bit-rate. Sounds like another bug. Did you create a separate issue report for that?

Yes, while in a call. I'm about to create a bug report but I want to compare the sound to your version of SiLK to theirs in the report.. but trying to get it up and running for 13.12.1 first so I can record the test.

**Comment by verticelo** [comment]
When I do "module show like silk" on 13.7.2 it shows the codec_silk.so but on 13.12.1 that is missing, it only shows the res_format_attr_silk.so.

*\* Update
When I run "make" for Asterisk I can see in the output that it never builds codec_silk.c to a .so file. Not sure why :/

Any idea?

**Comment by traud** [comment]
Please, try again.

**Comment by verticelo** [comment]
Patch works great now! Thank you. I'm going to run some quality tests tomorrow and I will let you know the outcome here.

I also created this ticket FYI:
https://issues.asterisk.org/jira/browse/ASTERISK-26564

**Comment by verticelo** [comment]
Hi again,

I have tested and everything seems to be working great! Thank you for your work on this.

I've found another bug that using FEC or DTX yields extremely bad sound quality for music on hold. I'm going to log that against the JIRA tracker as well since it also affects Digiums Opus binary.

**Comment by verticelo** [comment]
I'm going to go ahead and close this ticket. Thank you so much for your help.

I've logged two tickets so far against the Asterisk project for bugs in sound quality with their releases.
